# Generated by Django 5.2.8 on 2025-12-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='chat_id',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='chat_title',
            new_name='group_title',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='raw_text',
            new_name='order_text',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='clean_text',
        ),
        migrations.RemoveField(
            model_name='order',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='location_lng',
        ),
        migrations.RemoveField(
            model_name='order',
            name='source',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
